apiVersion: v1
kind: Namespace
metadata:
  name: my-nginx-5gvjif
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-5gvjif
  namespace: my-nginx-5gvjif
  labels:
    name: nginx-5gvjif
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx-5gvjif
  template:
    metadata:
      namespace: my-nginx-5gvjif
      labels:
        name: nginx-5gvjif
    spec:
      containers:
      - name: nginx-5gvjif
        image: nginx
        ports:
        - containerPort: 80

